Repository ekline-io/ekline-github-action, pull requests merged in 2024-07, with the labels that each got.

#34 Updated entrypoint.sh to run ekline on changed files
  entrypoint.sh
Labels: bump:minor

#35 Update cli to v7.4.2
  Dockerfile
Labels: bump:minor

#36 fix: entrypoint.sh to work with empty output.jsonl
  entrypoint.sh
Labels: bug, bump:patch

#38 [FIX] Coment only if there is an output
  entrypoint.sh
Labels: bump:patch

#40 fix: added enable_ai_suggestions input
  action.yml
Labels: bump:patch

#41 Update: fixed incorrect AI Suggestion
  Dockerfile
Labels: bump:patch

#42 Update Dockerfile
  Dockerfile
Labels: bump:minor

#44 fix: revert to vale 3.4.2
  Dockerfile
Labels: bug, bump:patch

#45 AI suggestions
  Dockerfile
Labels: bump:minor
